#! /bin/sh
# postrm script for kdm
#     
# see: dh_installdeb(1)

set -e

case "$1" in
       remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
       ;;
       purge)
         rm -rf /var/lib/kdm /etc/kde2/kdm/kdmrc.backup
	 update-rc.d kdm remove >/dev/null
       ;;
       *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 0
      ;;

esac   

#DEBHELPER#

exit 0
